yarnPath: .yarn/releases/yarn-3.2.3.cjs
# nodeLinker: node-modules
packageExtensions:
  "@tanstack/react-query-persist-client@*":
    dependencies:
      "@tanstack/query-core": "*"
  "styled-components@*":
    dependencies:
      "react-is": "*"
pnpMode: "loose"
nmMode: hardlinks-global
enableGlobalCache: true
compressionLevel: 0