const DEFAULT_GATEWAY_URL = __DEFAULT_GATEWAY_URL__;
const DEFAULT_API_MULTIADDR = __DEFAULT_API_MULTIADDR__;
const DEFAULT_API_URL = __DEFAULT_API_URL__;
const FLIPSTARTER_CLIENT = __FLIPSTARTER_CLIENT__;
const FLIPSTARTER_CLIENT_IPNS = __FLIPSTARTER_CLIENT_IPNS__;
const FLIPSTARTER_CLIENT_RECORD = __FLIPSTARTER_CLIENT_RECORD__;
const ELECTRUM_SERVERS = __ELECTRUM_SERVERS__;
const PRELOAD_NODES = __PRELOAD_NODES__;
const DEV_TIPS_ADDRESS = __DEV_TIPS_ADDRESS__;

export {
  DEFAULT_GATEWAY_URL,
  DEFAULT_API_MULTIADDR,
  DEFAULT_API_URL,
  FLIPSTARTER_CLIENT,
  FLIPSTARTER_CLIENT_IPNS,
  FLIPSTARTER_CLIENT_RECORD,
  ELECTRUM_SERVERS,
  PRELOAD_NODES,
  DEV_TIPS_ADDRESS
}